name: Java Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'

    - name: Show Java version
      run: "java -version"

    - name: Build with Maven
      run: mvn clean install --file pom.xml

    - name: Run unit tests
      run: |
        if [ -d "src/test/java" ]; then
          mvn test
        else
          echo "No unit tests found."
        fi
